// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY_HERE', // Replace with environment variable
    appId: 'YOUR_WEB_APP_ID_HERE', // Replace with environment variable
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE', // Replace with environment variable
    projectId: 'YOUR_PROJECT_ID_HERE', // Replace with environment variable
    authDomain: 'YOUR_AUTH_DOMAIN_HERE', // Replace with environment variable
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE', // Replace with environment variable
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE', // Replace with environment variable
    appId: 'YOUR_ANDROID_APP_ID_HERE', // Replace with environment variable
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE', // Replace with environment variable
    projectId: 'YOUR_PROJECT_ID_HERE', // Replace with environment variable
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE', // Replace with environment variable
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE', // Replace with environment variable
    appId: 'YOUR_IOS_APP_ID_HERE', // Replace with environment variable
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE', // Replace with environment variable
    projectId: 'YOUR_PROJECT_ID_HERE', // Replace with environment variable
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE', // Replace with environment variable
    iosBundleId: 'YOUR_IOS_BUNDLE_ID_HERE', // Replace with environment variable
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY_HERE', // Replace with environment variable
    appId: 'YOUR_WINDOWS_APP_ID_HERE', // Replace with environment variable
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE', // Replace with environment variable
    projectId: 'YOUR_PROJECT_ID_HERE', // Replace with environment variable
    authDomain: 'YOUR_AUTH_DOMAIN_HERE', // Replace with environment variable
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE', // Replace with environment variable
  );
}
