// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvwkWHTZ5qHJWxq94NaeYNRaiu-OLo8e0',
    appId: '1:480773029928:web:d585982c37876a8c1e351d',
    messagingSenderId: '480773029928',
    projectId: 'goal-play',
    authDomain: 'goal-play.firebaseapp.com',
    storageBucket: 'goal-play.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBboBdcXt9hthYVgncRtN8VG9S_ZXimVeg',
    appId: '1:480773029928:android:9d726b88dc7fb80a1e351d',
    messagingSenderId: '480773029928',
    projectId: 'goal-play',
    storageBucket: 'goal-play.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlXXYMMZ6H_9awtIpcTEc9JJ098AqEG5o',
    appId: '1:480773029928:ios:cd5a90f56bf339c01e351d',
    messagingSenderId: '480773029928',
    projectId: 'goal-play',
    storageBucket: 'goal-play.firebasestorage.app',
    iosBundleId: 'com.example.goalPlay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvwkWHTZ5qHJWxq94NaeYNRaiu-OLo8e0',
    appId: '1:480773029928:web:bb769862b5c704e31e351d',
    messagingSenderId: '480773029928',
    projectId: 'goal-play',
    authDomain: 'goal-play.firebaseapp.com',
    storageBucket: 'goal-play.firebasestorage.app',
  );
}
